//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.ModeloEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_UNIDAD_MEDIDA
    {
        public CAT_UNIDAD_MEDIDA()
        {
            this.TBL_DETALLE_COMPRA = new HashSet<TBL_DETALLE_COMPRA>();
            this.TBL_DETALLE_FACT = new HashSet<TBL_DETALLE_FACT>();
            this.TBL_PRODUCTO = new HashSet<TBL_PRODUCTO>();
        }
    
        public int ID_UNIDAD_MEDIDA { get; set; }
        public string UM_DESCRIPCION { get; set; }
        public Nullable<int> UNIDADES { get; set; }
    
        public virtual ICollection<TBL_DETALLE_COMPRA> TBL_DETALLE_COMPRA { get; set; }
        public virtual ICollection<TBL_DETALLE_FACT> TBL_DETALLE_FACT { get; set; }
        public virtual ICollection<TBL_PRODUCTO> TBL_PRODUCTO { get; set; }
    }
}
