//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.ModeloEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_CIUDAD
    {
        public CAT_CIUDAD()
        {
            this.CAT_BODEGA = new HashSet<CAT_BODEGA>();
            this.DATOSPERSONA = new HashSet<DATOSPERSONA>();
        }
    
        public int ID_CIUDAD { get; set; }
        public string NOMBRE_CIUDAD { get; set; }
        public Nullable<int> ID_DEPARTAMENTO_CIUDAD { get; set; }
    
        public virtual ICollection<CAT_BODEGA> CAT_BODEGA { get; set; }
        public virtual ICollection<DATOSPERSONA> DATOSPERSONA { get; set; }
        public virtual CAT_DEPARTAMENTO CAT_DEPARTAMENTO { get; set; }
    }
}
