//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.ModeloEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_SEXO
    {
        public CAT_SEXO()
        {
            this.DATOSPERSONA = new HashSet<DATOSPERSONA>();
        }
    
        public int ID_SEXO { get; set; }
        public string SEXO { get; set; }
    
        public virtual ICollection<DATOSPERSONA> DATOSPERSONA { get; set; }
    }
}
