//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.ModeloEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_UNIDADMEDIDA_ENVASE
    {
        public CAT_UNIDADMEDIDA_ENVASE()
        {
            this.TBL_DETALLE_COMPRA = new HashSet<TBL_DETALLE_COMPRA>();
            this.TBL_EXITENCIA = new HashSet<TBL_EXITENCIA>();
        }
    
        public int ID_UNIDAD_ENVASE { get; set; }
        public string DESCRIPCION_ENVASE_UNIDAD { get; set; }
    
        public virtual ICollection<TBL_DETALLE_COMPRA> TBL_DETALLE_COMPRA { get; set; }
        public virtual ICollection<TBL_EXITENCIA> TBL_EXITENCIA { get; set; }
    }
}
