//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.ModeloEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TIPO_TELEFONO
    {
        public CAT_TIPO_TELEFONO()
        {
            this.CAT_TELEFONO = new HashSet<CAT_TELEFONO>();
        }
    
        public int ID_TIPO_TELEFONO { get; set; }
        public string TIPO_TELEFONO { get; set; }
        public string DESCRIPCION_TIPO_TELEFONO { get; set; }
    
        public virtual ICollection<CAT_TELEFONO> CAT_TELEFONO { get; set; }
    }
}
