//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.ModeloEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_MiscelaneaConnyEntities : DbContext
    {
        public DB_MiscelaneaConnyEntities()
            : base("name=DB_MiscelaneaConnyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<AspNetRoles> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public DbSet<AspNetUsers> AspNetUsers { get; set; }
        public DbSet<CAT_BODEGA> CAT_BODEGA { get; set; }
        public DbSet<CAT_CIUDAD> CAT_CIUDAD { get; set; }
        public DbSet<CAT_DEPARTAMENTO> CAT_DEPARTAMENTO { get; set; }
        public DbSet<CAT_PAIS> CAT_PAIS { get; set; }
        public DbSet<CAT_PROVEEDOR> CAT_PROVEEDOR { get; set; }
        public DbSet<CAT_SEXO> CAT_SEXO { get; set; }
        public DbSet<CAT_TELEFONO> CAT_TELEFONO { get; set; }
        public DbSet<CAT_TIPO_PRODUCTO> CAT_TIPO_PRODUCTO { get; set; }
        public DbSet<CAT_TIPO_TELEFONO> CAT_TIPO_TELEFONO { get; set; }
        public DbSet<CAT_UNIDAD_MEDIDA> CAT_UNIDAD_MEDIDA { get; set; }
        public DbSet<CAT_UNIDADMEDIDA_ENVASE> CAT_UNIDADMEDIDA_ENVASE { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<DATOSPERSONA> DATOSPERSONA { get; set; }
        public DbSet<PRODUCTO_PROVEEDOR> PRODUCTO_PROVEEDOR { get; set; }
        public DbSet<TBL_COMPRA> TBL_COMPRA { get; set; }
        public DbSet<TBL_DETALLE_COMPRA> TBL_DETALLE_COMPRA { get; set; }
        public DbSet<TBL_DETALLE_FACT> TBL_DETALLE_FACT { get; set; }
        public DbSet<TBL_EXITENCIA> TBL_EXITENCIA { get; set; }
        public DbSet<TBL_FACTURA> TBL_FACTURA { get; set; }
        public DbSet<TBL_PRODUCTO> TBL_PRODUCTO { get; set; }
        public DbSet<TBL_PROMOCIONES> TBL_PROMOCIONES { get; set; }
        public DbSet<TblDevoluciones> TblDevoluciones { get; set; }
        public DbSet<TblMarca> TblMarca { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
