//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.ModeloEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_PROVEEDOR
    {
        public int ID_PRODUCTO { get; set; }
        public int ID_PROVEEDOR { get; set; }
        public int IdProductoProveedor { get; set; }
    
        public virtual CAT_PROVEEDOR CAT_PROVEEDOR { get; set; }
        public virtual TBL_PRODUCTO TBL_PRODUCTO { get; set; }
    }
}
