//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.ModeloEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTO
    {
        public TBL_PRODUCTO()
        {
            this.PRODUCTO_PROVEEDOR = new HashSet<PRODUCTO_PROVEEDOR>();
            this.TBL_DETALLE_COMPRA = new HashSet<TBL_DETALLE_COMPRA>();
            this.TBL_DETALLE_FACT = new HashSet<TBL_DETALLE_FACT>();
            this.TBL_EXITENCIA = new HashSet<TBL_EXITENCIA>();
            this.TblDevoluciones = new HashSet<TblDevoluciones>();
        }
    
        public int ID_PRODUCTO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public string DESCRIPCION_PRODUCTO { get; set; }
        public Nullable<int> ID_TIPO_PRODUCTO { get; set; }
        public Nullable<int> ID_UNIDAD_MEDIDA { get; set; }
        public Nullable<int> ID_MARCA { get; set; }
    
        public virtual CAT_TIPO_PRODUCTO CAT_TIPO_PRODUCTO { get; set; }
        public virtual CAT_UNIDAD_MEDIDA CAT_UNIDAD_MEDIDA { get; set; }
        public virtual ICollection<PRODUCTO_PROVEEDOR> PRODUCTO_PROVEEDOR { get; set; }
        public virtual ICollection<TBL_DETALLE_COMPRA> TBL_DETALLE_COMPRA { get; set; }
        public virtual ICollection<TBL_DETALLE_FACT> TBL_DETALLE_FACT { get; set; }
        public virtual ICollection<TBL_EXITENCIA> TBL_EXITENCIA { get; set; }
        public virtual TblMarca TblMarca { get; set; }
        public virtual ICollection<TblDevoluciones> TblDevoluciones { get; set; }
    }
}
