//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.ModeloEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_COMPRA
    {
        public TBL_COMPRA()
        {
            this.TBL_DETALLE_COMPRA = new HashSet<TBL_DETALLE_COMPRA>();
        }
    
        public int ID_COMPRA { get; set; }
        public Nullable<System.DateTime> FECHA_COMPRA { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> CANTIDAD_PAGO { get; set; }
        public Nullable<decimal> CAMBIO { get; set; }
    
        public virtual ICollection<TBL_DETALLE_COMPRA> TBL_DETALLE_COMPRA { get; set; }
    }
}
