//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.ModeloEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PROMOCIONES
    {
        public int ID_PROMOCION { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FINAL { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PRECIO_PROMOCION { get; set; }
        public string CANTIDAD { get; set; }
    }
}
