//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.ModeloEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.TBL_FACTURA = new HashSet<TBL_FACTURA>();
        }
    
        public int ID_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public byte[] CONTRASENA_USUARIO { get; set; }
        public Nullable<int> ID_PERSONA_USUARIO { get; set; }
    
        public virtual DATOSPERSONA DATOSPERSONA { get; set; }
        public virtual ICollection<TBL_FACTURA> TBL_FACTURA { get; set; }
    }
}
